; Generated by AutoGUI 2.6.2
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

Gui Add, Text, x26 y43 w118 h0 +0x200, Text
Gui Add, Text, x16 y16 w156 h35 +0x200, 請選擇要執行的應用程式
Gui Add, Button, gbtnWord x16 y80 w80 h23, &1 Word
Gui Add, Button, gbtnExcel x120 y80 w80 h23, &2 Excel
Gui Add, Button, gbtnNotepad x224 y80 w80 h23, &3 Notepad

Gui Show, w344 h148, Window
ReturnnBytes := Base64Dec( Base64ImageData, Bin )

File := FileOpen("ahkiconnew.png", "w")
File.RawWrite(Bin, nBytes)
File.Close()nBytes := Base64Dec( Base64ImageData, Bin )

File := FileOpen("ahkiconnew.png", "w")
File.RawWrite(Bin, nBytes)
File.Close()nBytes := Base64Dec( Base64ImageData, Bin )

File := FileOpen("ahkiconnew.png", "w")
File.RawWrite(Bin, nBytes)
File.Close()nBytes := Base64Dec( Base64ImageData, Bin )

File := FileOpen("ahkiconnew.png", "w")
File.RawWrite(Bin, nBytes)
File.Close()nBytes := Base64Dec( Base64ImageData, Bin )

File := FileOpen("ahkiconnew.png", "w")
File.RawWrite(Bin, nBytes)
File.Close()nWord(CtrlHwnd, GuiEvent, EventInfo, ErrLevel := "") {
  ;Run "C:\Program Files\Microsoft Office\root\Office16\WINWORD.EXE"
  ExitApp, 1
}

btnExcel:
  ;Run Excel
  ExitApp, 2
Return

btnNotepad:
  ;Run Notepad
  ExitApp 3
Return

GuiEscape:
GuiClose:
  ExitApp
; Generated by AutoGUI 2.6.2
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

Gui Add, Text, x26 y43 w118 h0 +0x200, Text
Gui Add, Text, x16 y16 w156 h35 +0x200, 請選擇要執行的應用程式
Gui Add, Button, gbtnWord x16 y80 w80 h23, &1 Word
Gui Add, Button, gbtnExcel x120 y80 w80 h23, &2 Excel
Gui Add, Button, gbtnNotepad x224 y80 w80 h23, &3 Notepad

Gui Show, w344 h148, Window
ReturnnBytes := Base64Dec( Base64ImageData, Bin )

File := FileOpen("ahkiconnew.png", "w")
File.RawWrite(Bin, nBytes)
File.Close()nBytes := Base64Dec( Base64ImageData, Bin )

File := FileOpen("ahkiconnew.png", "w")
File.RawWrite(Bin, nBytes)
File.Close()nBytes := Base64Dec( Base64ImageData, Bin )

File := FileOpen("ahkiconnew.png", "w")
File.RawWrite(Bin, nBytes)
File.Close()nBytes := Base64Dec( Base64ImageData, Bin )

File := FileOpen("ahkiconnew.png", "w")
File.RawWrite(Bin, nBytes)
File.Close()nBytes := Base64Dec( Base64ImageData, Bin )

File := FileOpen("ahkiconnew.png", "w")
File.RawWrite(Bin, nBytes)
File.Close()nWord(CtrlHwnd, GuiEvent, EventInfo, ErrLevel := "") {
  ;Run "C:\Program Files\Microsoft Office\root\Office16\WINWORD.EXE"
  ExitApp, 1
}

btnExcel:
  ;Run Excel
  ExitApp, 2
Return

btnNotepad:
  ;Run Notepad
  ExitApp 3
Return

GuiEscape:
GuiClose:
  ExitApp
; Generated by AutoGUI 2.6.2
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

Gui Add, Text, x26 y43 w118 h0 +0x200, Text
Gui Add, Text, x16 y16 w156 h35 +0x200, 請選擇要執行的應用程式
Gui Add, Button, gbtnWord x16 y80 w80 h23, &1 Word
Gui Add, Button, gbtnExcel x120 y80 w80 h23, &2 Excel
Gui Add, Button, gbtnNotepad x224 y80 w80 h23, &3 Notepad

Gui Show, w344 h148, Window
ReturnnBytes := Base64Dec( Base64ImageData, Bin )

File := FileOpen("ahkiconnew.png", "w")
File.RawWrite(Bin, nBytes)
File.Close()nBytes := Base64Dec( Base64ImageData, Bin )

File := FileOpen("ahkiconnew.png", "w")
File.RawWrite(Bin, nBytes)
File.Close()nBytes := Base64Dec( Base64ImageData, Bin )

File := FileOpen("ahkiconnew.png", "w")
File.RawWrite(Bin, nBytes)
File.Close()nBytes := Base64Dec( Base64ImageData, Bin )

File := FileOpen("ahkiconnew.png", "w")
File.RawWrite(Bin, nBytes)
File.Close()nBytes := Base64Dec( Base64ImageData, Bin )

File := FileOpen("ahkiconnew.png", "w")
File.RawWrite(Bin, nBytes)
File.Close()nWord(CtrlHwnd, GuiEvent, EventInfo, ErrLevel := "") {
  ;Run "C:\Program Files\Microsoft Office\root\Office16\WINWORD.EXE"
  ExitApp, 1
}

btnExcel:
  ;Run Excel
  ExitApp, 2
Return

btnNotepad:
  ;Run Notepad
  ExitApp 3
Return

GuiEscape:
GuiClose:
  ExitApp
